### PR TITLE
Add Travis and build wheels

### PR DESCRIPTION
**Pull request by stephengroat**
I can show how to auto-upload the wheels to pypi, it would be a big help to me if they were there (https://docs.travis-ci.com/user/deployment/pypi/)

i can add windows with appveyor if it's important

### CODE REVIEW

**Comment by sgeto** [comment]
great job
actually reminds me of handing in a PR
I worked on it for while but never finalized it. Python is not is not my favorite language.

Anyways if this doesn't get merged, I might borrow some of it if it's okay.
My fork is here https://github.com/sgeto/libdnet . Take what you need from it. 
I'll send a PR once I'm happy with it and free

**Comment by stephengroat** [comment]
If you're willing to maintain and publish the wheels to pypi, just let me
know what help you need

**Comment by sgeto** [comment]
sounds good. I guess can do that. I'm already maintaining libdnet cus it's part of the lua bindings of another project I'm taking care of. Long story...
I did some stuff with dnet's python bindings (python 3 support and silenced some compiler warnigs), but really just for fun.
What do you have in mind?

**Comment by stephengroat** [comment]
@sgeto any idea of how to run the tests? do you know what make command it is?

**Comment by sgeto** [comment]
`make check`
but you have to install the python module first... or make sure it's somewhat reachable by the python interpreter. Whatever is more convenient I guess...

**Comment by stephengroat** [comment]
does running `make check` run any tests without the python path being correct? shouldn't it run the standard c tests?

**Comment by sgeto** [comment]
"make check" only tests the python module. You have to manually run the unit tests. If the python path isn't set to include to the binding, then the test will fail...

**Pull request closed without merging**
